
name: tests

on: [push, "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      run:
        ./update_libs.sh -f && make tests
    - name: Run tests
      run: |
        ./tests
      